project: 
  type: website
  output-dir: "." 

website:
  title: "Carolyn Mack"
  navbar:
    # background: "#1c4982"
    pinned: true
    left:
      - text: Blog
        href: blog-listing.qmd
      - text: "Python Dadta Analysis"
        menu:
          - text: "pandas"
            href: pandas_basics.ipynb
          - text: "seaborn"
            href: seaborn_basics.ipynb
            
format:
  html:
    theme: 
      light: flatly # flatly sandstone yeti united litera journal
      dark: darkly #  darkly cyborg slate solra superhero
    mainfont: system-ui; 
    highlight-style: atom-one  # atom-one espresso
    css: styles.css
    toc: false
    include-after-body: target_blank.html

